### ISSUE TITLE
error: Cannot call method 'on' of undefined

### ISSUE THREAD

**Issue by theutz** [jnordberg/wintersmith-livereload#4]
When I install this plugin using either `npm install [-g] wintersmith-livereload` or `wintersmith plugin install livereload`, I can't run `wintersmith preview` anymore without getting:

> error Cannot call method 'on' of undefined

and then a quick exit from the process.

**Comment by esopian** [comment]
I just hit this bug as well.  The problem I was having was because i was running against the 0.10.x node branch.  Switching to using 0.12.x fixed the issue for me.  ymmv
