### ISSUE TITLE
Files 'ignored' in config.json will not trigger reload

### ISSUE THREAD

**Issue by Jayphen** [jnordberg/wintersmith-livereload#7]
I know that this is most likely intended behaviour, but perhaps there's a solution to my problem.

In my `config.json` I have the following

```
  "ignore": [
    "**/.DS_Store",
    "**/src",
    "vendor/normalize*",
    "**/.bower.json",
    "styles/elements",
    "styles/mixins"
  ]
```

The directories under 'styles' are in there because I don't want them to be processed by `wintersmith build`. However, this means that my page does not reload when I edit those files.

What is the solution here? Can I have a separate ignore list specifically for Livereload?

**Comment by jnordberg** [comment]
Yeah, no way to do this, files ignored completely bypass wintersmith's pipeline and will not trigger a change event. A workaround is to use `wintersmith-static` instead of ignore and remove the files from the output after building.

And sorry for the ultra-slow response :)

**Comment by jnordberg** [comment]
Was thinking about this and decided to change the behaviour in wintersmith to emit change events for ignored files as well. So as of 2.4.1 changes to ignored files will be reloaded as well.
